# Generated by Django 4.2.11 on 2024-04-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='review_name')),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField(max_length=300)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
