# Generated by Django 4.2.11 on 2024-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(help_text='enter valid email', max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(help_text='enter text field', max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=250, verbose_name='your_name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.IntegerField(help_text='enter phone number'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
