# Generated by Django 4.2.11 on 2024-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0002_alter_review_email_alter_review_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
