# Generated by Django 4.2.11 on 2024-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_alter_review_email_alter_review_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('your_message', models.TextField(max_length=500)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
